runtime: python310  # Replace with your Python version
entrypoint: python main.py  # Replace with your entrypoint file

instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 15
  target_throughput_utilization: 0.5
